[pyprland]
plugins = ["scratchpads"]

[scratchpads.term_kitty]
animation = "fromRight"
command = "kitty --class term_kitty"
class = "term_kitty"
size = "75% 60%"
max_size = "1920px 100%"
focus_on_visible = true
lazy = true
